apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vpn-payment
  namespace: vpn-payment
  labels:
    app.kubernetes.io/name: vpn-payment
    app.kubernetes.io/instance: vpn-payment
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: vpn-payment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vpn-payment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
